[Task] Ajusta plugin do vite para adicionar preset
uxshop/storefront-core pull request #103
Opened 2022-11-17 17:26 UTC by kevenssousa

* Criado metodos que carregam os arquivos de presets no build

2022-11-17 17:38 UTC, simaomeyrerdooca requested changes

2022-11-17 17:38 UTC, simaomeyrerdooca commented on src/plugin/SchemaService.ts
>    private writeSchemaBundle(content, dir) {
podemos renomear essa função para algo mais genérico como `writeBundleFile` visto que ela é responsável somente por 'escrever' os arquivos de bundle, independente do tipo

2022-11-17 17:38 UTC, simaomeyrerdooca commented on src/plugin/SchemaService.ts
> +      throw new Error(`Error returning sections bundle ${error}`)
Error returning **_presets_** bundle

2022-11-17 17:38 UTC, simaomeyrerdooca commented on src/plugin/SchemaService.ts
> +        fs.writeFile(dir, typeof content === 'string' ? content : JSON.stringify(content), error => {
tanto sections como settings são gerados a partir dessa função, é necessária essa validação `typeof content === 'string'`?

2022-11-17 18:37 UTC, simaomeyrerdooca requested changes

2022-11-17 18:37 UTC, simaomeyrerdooca commented on src/plugin/SchemaService.ts
> +        let pathDir = `${themePath}/public/presets/preset-${index}.json`
aqui precisamos utilizar o nome do arquivo original

2022-11-18 19:27 UTC, simaomeyrerdooca approved these changes

2022-11-24 11:56 UTC, diovaniBelleboni approved these changes

2022-11-24 11:58 UTC, merged