[Task] Criar módulo de slug na storefront-core
uxshop/storefront-core pull request #120
Opened 2023-01-05 16:16 UTC by kevenssousa

Criado modulo que busca registro de acordo com o slug

2023-01-05 16:50 UTC, diovaniBelleboni approved these changes

2023-01-05 16:53 UTC, simaomeyrerdooca requested changes

2023-01-05 16:53 UTC, simaomeyrerdooca commented on src/modules/slug/SlugType.ts
> +export interface SlugResponse {
essa interface genérica creio que não seja necessária, a propriedade `data` sempre é`string`

2023-01-05 16:53 UTC, simaomeyrerdooca commented on src/types/BroadcastEventEmitType.ts
> +  user = 'User'
por convenção do typescript usamos enum como PascalCase ou UPPERCASE

2023-01-06 11:11 UTC, tiagotermedooca requested changes

2023-01-06 11:11 UTC, tiagotermedooca commented on src/modules/slug/SlugService.ts
> +      BroadcastService.emit(eventType, result)
Dessa forma acredito que teremos problemas com os eventos já vinculados, pois o esperado é `PascalCase`, e está sendo passado`UPPERCASE`

2023-01-06 12:13 UTC, tiagotermedooca requested changes

2023-01-06 12:13 UTC, tiagotermedooca commented on src/modules/slug/SlugService.ts
> +  showcase: 'Showcase',
colocar showcase como Produto tbm

2023-01-06 19:37 UTC, simaomeyrerdooca approved these changes

2023-01-12 10:32 UTC, tiagotermedooca approved these changes

2023-01-12 12:21 UTC, merged