[hotfix] Revisa dados de retorno de Blog
uxshop/storefront-core pull request #133
Opened 2023-02-05 15:42 UTC by Lima08

## Revisar os dados de retorno de Blog 
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-7?workitem=5700)

Changes:
- Atualiza `type` do Blog
- Modifica retorno do `getCategoryLink`

2023-02-06 12:23 UTC, simaomeyrerdooca requested changes

2023-02-06 12:23 UTC, simaomeyrerdooca commented on src/services/navigation/navigation-service.ts
> +    return `/blog/${categorySlug}`
aqui na verdade precisamos alterar a função `getBlogCategoryLink` caso o problema seja no link pra acessas as categorias de blog, a `getCategoryLink` é usada pra categoria de produto

2023-02-07 13:16 UTC, Lima08 commented on src/services/navigation/navigation-service.ts
> +    return `/blog/${categorySlug}`
Nossa, essa foi cagada, Mals XD

2023-02-07 16:44 UTC, simaomeyrerdooca approved these changes

2023-02-07 16:44 UTC, merged