[Task] Alteradas propriedades para camelCase
uxshop/storefront-core pull request #74
Opened 2022-11-04 20:12 UTC by simaomeyrerdooca

2022-11-04 20:16 UTC, kevenssousa approved these changes

2022-11-04 20:17 UTC, tiagotermedooca requested changes

2022-11-04 20:17 UTC, tiagotermedooca commented on src/types/product/BrandTypes.ts
> +  isActive?: nullable<boolean>
remover nullable

2022-11-04 20:19 UTC, diovaniBelleboni approved these changes

2022-11-04 20:23 UTC, kevenssousa approved these changes

2022-11-05 23:11 UTC, tiagotermedooca approved these changes

2022-11-07 11:30 UTC, merged